FROM node as builder

# Create app directory
WORKDIR /app

# Install app dependencies
COPY ./server/package*.json .
RUN npm install\
        && npm install typescript -g

ADD ../shared .
COPY . .

RUN npm run build

FROM node:slim

ENV NODE_ENV production

# Create app directory
WORKDIR /app

# Install app dependencies
ADD ../shared /app
COPY ./server/package*.json .
RUN npm install --production\
        && npm install typescript -g
COPY --from=builder /usr/src/app/dist ./dist

USER node
EXPOSE 3000
CMD [ "node", "dist/server/index.js" ]

### Run from parent directory
### docker build -t nodejs-server -f ./server/dockerfile .